{
 "title": "WatchDog",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(watchdog_endpoint_validation,environment)"
    }
   },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(watchdog_endpoint_validation{environment=~\"$environment\"},group)"
    }
   },
   {
    "name": "route",
    "label": "Route",
    "query": {
     "query": "label_values(watchdog_endpoint_validation{environment=~\"$environment\", group=~\"$group\"},route)"
    }
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(watchdog_endpoint_validation{environment=~\"$environment\", group=~\"$group\", route=~\"$route\"},endpoint)"
    }
   },
   {
    "name": "status",
    "label": "Status",
    "query": {
     "query": "label_values(watchdog_endpoint_validation{environment=~\"$environment\", group=~\"$group\", route=~\"$route\", endpoint=~\"$endpoint\"},status)"
    }
   },
   {
    "name": "is_error",
    "label": "Error",
    "query": {
     "query": "label_values(watchdog_endpoint_validation{environment=~\"$environment\", group=~\"$group\", route=~\"$route\", endpoint=~\"$endpoint\", status=~\"$status\"},is_error)"
    }
   },
   { "name": "max_left_days", "label": "Certs Max Left Days", "query": "1,3,7,14,31,90" },
   { "name": "top", "label": "Top", "query": "3,5,10,15,25,50,100" }
  ]
 },
 "panels": [
  {
   "title": "All Invalid Endpoints",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(watchdog_endpoint_validation{status!=\"valid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "watchdog_endpoint_validation{status!=\"valid\", environment=~\"$environment\", group=~\"$group\", route=~\"$route\", endpoint=~\"$endpoint\", is_error=~\"$is_error\"}",
     "legendFormat": "{{status}} - {{group}} - {{url}} - {{route}}"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "time() - max_over_time(timestamp(watchdog_endpoint_validation{environment=~\"$environment\", group=~\"$group\", route=~\"$route\", endpoint=~\"$endpoint\", status=~\"$status\", is_error=~\"$is_error\"})[5m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top $top Endpoints Duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($top, watchdog_endpoint_duration_seconds{environment=~\"$environment\", group=~\"$group\", route=~\"$route\", endpoint=~\"$endpoint\", status=~\"$status\", is_error=~\"$is_error\"})",
     "legendFormat": "{{group}} - {{endpoint}} - {{route}} - {{status}}"
    }
   ]
  },
  {
   "title": "Expiring TLS Certificates ($max_left_days days)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "min by (cert_cn) (watchdog_endpoint_tls_cert_days_left{environment=~\"$environment\", group=~\"$group\", route=~\"$route\", endpoint=~\"$endpoint\"})<$max_left_days",
     "legendFormat": "{{cert_cn}} "
    }
   ]
  },
  {
   "title": "TLS Certificates",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "min by (cert_cn, cert_is_ca, cert_issuer_cn, cert_position, cert_serial) (watchdog_endpoint_tls_cert_days_left{environment=~\"$environment\", group=~\"$group\", route=~\"$route\", endpoint=~\"$endpoint\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}